resources:
- ../base
- ./namespace.yaml

namePrefix: dev-

namespace: dev

patches:
- target:
    kind: Deployment
    name: dep.*
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: deploy
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:latest
